// SORA NETWORK //
export const XOR_ADDRESS =
  '0x0200000000000000000000000000000000000000000000000000000000000000';
export const XSTUSD_ADDRESS =
  '0x0200080000000000000000000000000000000000000000000000000000000000';
export const RESERVE_ADDRESS =
  'cnTQ1kbv7PBNNQrEb1tZpmK7eE2hQTwktcdewhc55bpkDrYBX';

// COIN GECKO IDS //
export const SYMBOLS_AND_GECKO_IDS = {
  MANA: 'decentraland',
  GRT: 'the-graph',
  HUSD: 'husd',
  XOR: 'sora',
  VAL: 'sora-validator-token',
  CREAM: 'cream-2',
  XFUND: 'xfund',
  COMP: 'compound-governance-token',
  UNI: 'uniswap',
  LINK: 'chainlink',
  AAVE: 'aave',
  DEO: 'demeter',
  OCEAN: 'ocean-protocol',
  FIS: 'stafi',
  DAI: 'dai',
  IDEX: 'aurora-dao',
  HT: 'huobi-token',
  HMX: 'hermes-dao',
  USDC: 'usd-coin',
  UST: 'terrausd',
  SUSHI: 'sushi',
  HOT: 'holotoken',
  KNC: 'kyber-network',
  DIA: 'dia-data',
  CAPS: 'coin-capsule',
  PDEX: 'polkadex',
  AKRO: 'akropolis',
  USDT: 'tether',
  CERES: 'ceres',
  LEO: 'leo-token',
  BUSD: 'binance-usd',
  NEXO: 'nexo',
  ETH: 'ethereum',
  REN: 'republic-protocol',
  PHA: 'pha',
  BAT: 'basic-attention-token',
  RLC: 'iexec-rlc',
  CRV: 'curve-dao-token',
  XRT: 'robonomics-network',
  PSWAP: 'polkaswap',
  OKB: 'okb',
  UMI: 'umi-digital',
  KSM: 'kusama',
  MATIC: 'matic-network',
  UMA: 'uma',
  AGI: 'singularitynet',
  WCFG: 'wrapped-centrifuge',
  RARE: 'unique-one',
  REEF: 'reef',
  DOT: 'polkadot',
};
